Repository piotr-oles/as-proto, pull requests merged in 2022-01, with the labels that each got.

#1 feat: setup ci
  .github/workflows/ci.yml
  .gitignore
  LICENSE
  README.md
  lerna.json
  package.json
  packages/as-proto-gen/package.json
  packages/as-proto/package.json
  yarn.lock
Labels: minor, released

#2 fix: make release on main branch working
  .gitignore
  package.json
  packages/as-proto-gen/package.json
  packages/as-proto/package.json
Labels: minor

#4 chore: add ci workflow for pull_request event
  .github/workflows/ci.yml
Labels: skip-release

#3 add length param to decode function
  packages/as-proto/assembly/Protobuf.ts
Labels: minor
