Repository piotr-oles/as-proto, pull requests merged in 2022-11, with the labels that each got.

#28 Support map fields
  package.json
  packages/as-proto-gen/package.json
  packages/as-proto-gen/src/generate/field.ts
  packages/as-proto-gen/src/generate/file.ts
  packages/as-proto-gen/src/generate/ref.ts
  tests/assembly/.gitignore
  tests/assembly/asconfig.json
  tests/assembly/test-all-types.ts
  tests/assembly/test-map-fields.ts
  tests/js/test-all-types.js
  tests/js/test-map-fields.js
  tests/prepare.js
  tests/proto/test.proto
  tests/proto/testbinary.proto
  tests/test-all-types.spec.js
  tests/test-all-types.spec.ts
  tests/test-map-fields.spec.js
Labels: minor

#33 fix code to compile with assemblyscript >= 0.23.
  package.json
  packages/as-proto/assembly/internal/FixedWriter.ts
  yarn.lock
Labels: patch

#34 Remove `getSafeName()` from `ScopeContext`
  packages/as-proto-gen/src/generate/message.ts
  packages/as-proto-gen/src/reserved-keywords.ts
  packages/as-proto-gen/src/scope-context.ts
  tests/as-proto-gen/reserved-keyword.spec.ts
  tests/as-proto-gen/scope-context.spec.ts
Labels: skip-release

#36 Update benchmark to use ESM bindings
  .github/workflows/benchmark.yml
  bench/as-proto/asconfig.json
  bench/as-proto/assembly/generated/.gitkeep
  bench/as-proto/src/static_aspr.ts
  bench/as-proto/tsconfig.json
  bench/data/.gitignore
  bench/data/assembly/asconfig.json
  bench/data/assembly/bench.ts
  bench/data/assembly/static_aspr.ts
  bench/data/assembly/tsconfig.json
  bench/data/static_aspr.d.ts
  bench/data/static_aspr.js
  bench/data/static_jspb.cjs
  bench/data/static_pbjs.cjs
  bench/index.cjs
  bench/index.js
  bench/prepare.js
  bench/prof.js
  bench/suite.cjs
  package.json
Labels: skip-release

#37 Improve file context by re-using scope context
  packages/as-proto-gen/src/file-context.ts
Labels: patch
